### ISSUE TITLE
wanna say thanks

### ISSUE THREAD

**Issue by Zhangsun321** [selvanair/openvpn-gui#6]
seems to work fine for me for what I need it to do.  THANK YOU SOO MUCH!!

**Comment by selvanair** [comment]
Thanks for the feedback. is this about the patch for the management timeout issue? If not, please let me know which issue was resolved.

**Comment by Zhangsun321** [comment]
oh.. for the entire umm 'version'  to allow more than 49 config files!!
seems to work fine so far..  will let you know if I have any problems!

**Comment by selvanair** [comment]
Oh, the 50+ configs issue discussed under issue #235. Thanks for testing.

That patch is not yet merged upstream -- I guess you are trying out the draft I posted. Please provide feedback in that thread (#235 on the upstream repo) or feel free to open a new issue there if you find anything that needs to be addressed.
